### ISSUE TITLE
Not reset password option

### ISSUE THREAD

**Issue by fungiboletus** [botpress/botpress-electron#1]
Hi,

It seems that you cannot reset the password on botpress-electron if you forgot it or wrote it wrong the first time.

**Comment by ptrckbp** [comment]
Sorry for the wait, and thanks for posting the first Issue!

As far as I know, there is no straightforward way to do this, but there is a way!

The botpress-electron downloads botpress binaries to 

`${osAppDataPath}/botpress-electron/binaries/${botpressVersion}.`

osAppDataPath depends on your operating system and should be one of : 
%APPDATA% on Windows
$XDG_CONFIG_HOME or ~/.config on Linux
~/Library/Application Support on macOS

botpressVersion should look like v12_26_12. 

Navigate inside using a file editor / terminal, then open `data/storage/core.sqlite` with some sql writer and run : `delete from strategy_default`. This command deletes all your users. When you re-open Botpress, it should ask you to create an account again.

**Comment by fungiboletus** [comment]
Thanks for the help. I eventually removed the whole `botpress-electron` folder the last time, the user didn't have a lot of work done yet. But next time I will use the sqlite query.

**Comment by ptrckbp** [comment]
Yup, that works too. If you don't care about existing bots you can do that. :)
